### ISSUE TITLE
Streamfield doesnt work

### ISSUE THREAD

**Issue by NathHorrigan** [tr11/wagtail-graphql#4]
Using streamfield blocks of any sort causes an error. I've tried this on my installation and the 'test_project' but I get the issue on both...

```
# models.py
from wagtail.core.fields import StreamField
from wagtail.core.models import Page
from wagtail.core.blocks import CharBlock
from wagtail.admin.edit_handlers import FieldPanel, StreamFieldPanel


class HomePage(Page):
    streamfield = StreamField([
        ('h2', CharBlock(icon="title", classname="title")),
    ], null=True, blank=True)

    content_panels = [
        FieldPanel('title', classname="full title"),
        StreamFieldPanel('streamfield'),
    ]
```

Error: `Could not import 'wagtail_graphql.schema.schema' for Graphene setting 'SCHEMA'. AttributeError: 'GraphQLScalarType' object has no attribute 'graphene_type'.`

**Comment by tr11** [comment]
Thank you for pointing this out. We are using this wrapper with StructBlocks only, so the issue never came up.  The reason is that the Graphene Union cannot use the scalar types, leading to a failure of streamfields that reference directly CharBlocks, IntBlocks, etc.

For scalar types the wrapper will now create a new type (StringBlock, for example) with two fields: value and field (name).

**Comment by NathHorrigan** [comment]
Brilliant, Thanks @tr11 !!
